### ISSUE TITLE
AS-path loops

### ISSUE THREAD

**Issue by ratulm** [arifogel/batfish#22]
It looks like BGP receivers in Batfish detect AS-path loops only by looking for their AS number in the first position of the AS-path. That would allow for loopy AS-paths such as A-X-Y-A-Z. In reality, such paths will not be allowed.

**Comment by arifogel** [comment]
That's not what was happening, but in any case I fixed AS-path checking in commit bc8ab6298273346457108e9ba8497e4475027e70
